### ISSUE TITLE
No way to load files into IIk more than once.

### ISSUE THREAD

**Issue by Raynes** [olabini/ioke#1]
Ioke needs a way to load files into IIk more than just once. It should check to see if the file has changed since the last time it was loaded, and if so, load it again.

**Comment by olabini** [comment]
So this is actually possible right now, albeit in a not fantastic way. Basically you can always say:
  eval(FileSystem readFully("path/to/your/file.ik"))
I will however leave this issue open so I can create a more proper way of handling this.

**Comment by Raynes** [comment]
That will come in handy.
