### ISSUE TITLE
Using operators with many lines

### ISSUE THREAD

**Issue by kinda** [olabini/ioke#3]
The following code triggers a TooFewArguments condition :

```
x = "Hello" +
  " there!"
```

Same issue with a simple assignment:

```
x =
  "Hi"
```

**Comment by vic** [comment]
Hi, 

I believe this aint a bug. In ioke, operators like "+" and "=" are just methods, they are not treated differently. So, for example, the following code means "call foo on x, then bar on the current context"

```
x foo 
   bar
```

The thing is that in ioke, the end of line represents a message terminator (that is, the end of a message chain), but if you really want to split a message into several lines you can always use a backslash before the end of line.

IIRC, the end of line is not treated as message terminator in a few cases like, following a comma, or inside an string literal.

```
      hello(to,
              the,
              world)
```

Greetings

**Comment by kinda** [comment]
Thanks vic, I understand your point, but since operators don't require parentheses to pass arguments (1 + 1 means 1 +(1)) the following code:

```
1 +
  1
```

could be interpreted as:

```
1 +(
  1)
```

But again, I understand your point and I can imagine the dilemma for the parser having to decide if "+" is a method call without parameters or not.
