### ISSUE TITLE
'evaluateOn' does not take account of the ground parameter

### ISSUE THREAD

**Issue by kinda** [olabini/ioke#4]
'Message evaluateOn(ground, receiver)' does not seem to take account of the 'ground' parameter:

```
mac = macro(call arguments first evaluateOn(call ground, self))

meth = method(
  x = 1
  mac(x println)
)

meth
```

Returns the following error:

```
*** - couldn't find cell 'x' on 'Ground' (Condition Error NoSuchCell)
```

**Comment by olabini** [comment]
This bug is incorrect. evaluateOn definitely takes into account the ground, but the ground is actually not used when something has an explicit receiver - and since you provide self, your example is actualy equivalent to writing
    self x println
which doesn't work.

**Comment by kinda** [comment]
Thanks Ola Bini. Slowly, the execution model of Ioke becomes clear to me. Indeed, the ground is used to evaluate the arguments.

Coming from Ruby, what is difficult for me to understand is that the ground and the self are not two separate things. In Ioke, we must think things more simply. In fact, the self is nothing but a cell set into a ground which has nothing to do with the Ruby bindings. Since the ground contains the self, we can't easily say "evaluate that with this ground and this self". So, what do you think of redefining the ground's self before calling evaluateOn?

```
mac = macro(
  let(call ground self, self,
    call arguments first evaluateOn(call ground)
  )
)

meth = method(
  x = 1
  y = 2
  y mac(x println. println)
)

meth
```

Which returns:

```
1
2
```

Although this is not very clean, it does what I had in mind at first with my misunderstanding of the method evaluateOn(ground, receiver).

**Comment by olabini** [comment]
I'm not sure what you're trying to achieve here, but to be it's very confusing. self is NOT just a cell on ground. and evaluateOn allows you to do exactly that, evaluateOn a specific ground and self. I'm not sure I understand what kind of code would ever need to be able to do the above. Can you show me what you're trying to do?

**Comment by kinda** [comment]
Well, imagine something like that:

```
window(
  f = field
  button("Print",
    f value println
    disable
  )
)
```

We have a window displaying a text field and a button named "Print". If we click on that button, the code corresponding to the last argument of the method button is executed. What the code should do is: 1) print the value of the text field which is referenced by a local variable defined in the surrounding context, 2) disable the button by calling the 'disable" method on the current self (the button). I know it sounds a little crazy but it is the kind of things I would like to achieve.

**Comment by olabini** [comment]
What you seem to want is a combination of both lexical scope AND object scope. In general, I try to avoid that in Ioke, since it's not possible to unify those two completely. I think the easiest solution for you might be to actually rewrite the code to be explicit (make the macro do a tree rewrite...)

**Comment by kinda** [comment]
Actually, the more I think about my little DSL and the more it seems wrong somehow... You just confirmed my feeling and I think I will go in a different direction. Changing the current self is not a good idea after all... I'm going to try something else. :)

Thanks again and keep going the good work, Ioke is such a wonderful language!
