### ISSUE TITLE
Failing spec for && operator when using new parser.

### ISSUE THREAD

**Issue by vic** [olabini/ioke#5]
The following spec is failing for me when using the new parser:

describe("New ioke parser",

  it("should correctly parse right hand side of && when its an assignment"
     Message fromText("foo && bar = baz ") code should == "foo &&(=(bar, baz))"
  )
)

Something in the new parser messed up. As a work-around I have to enclose 
(bar = baz) in braces.

**Comment by olabini** [comment]
Small fix and some test cases added to master for this. It should work fine now. Good catch! =)
